spring:
  datasource:
    url: jdbc:h2:mem:fabrickdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.JBossStandAloneJtaPlatform
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    com.orbyta_admission_quiz: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
fabrick:
  api:
    baseUrl: https://sandbox.platfr.io
    endpoints:
      accountBalanceEndpoint: /api/gbs/banking/v4.0/accounts/{accountId}/balance
      accountTransactionsEndpoint: /api/gbs/banking/v4.0/accounts/{accountId}/transactions
      moneyTransferEndpoint: /api/gbs/banking/v4.0/accounts/{accountId}/payments/money-transfers
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    expansion: none
server:
  port: 8080