spring:
  application:
    name: orbyta-quiz
  datasource:
    url: jdbc:h2:mem:fabrickdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    com.orbyta_admission_quiz: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
fabrick:
  api:
    baseUrl: https://sandbox.platfr.io
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    expansion: none
